const KEY_LAYOUTS = {
  EN: [
    {
      keyCode: 'Backquote',
      value: '`',
      shiftValue: '~',
      type: 'symbol',
    },
    {
      keyCode: 'Digit1',
      value: '1',
      shiftValue: '!',
      type: 'symbol',
    },
    {
      keyCode: 'Digit2',
      value: '2',
      shiftValue: '@',
      type: 'symbol',
    },
    {
      keyCode: 'Digit3',
      value: '3',
      shiftValue: '#',
      type: 'symbol',
    },
    {
      keyCode: 'Digit4',
      value: '4',
      shiftValue: '$',
      type: 'symbol',
    },
    {
      keyCode: 'Digit5',
      value: '5',
      shiftValue: '%',
      type: 'symbol',
    },
    {
      keyCode: 'Digit6',
      value: '6',
      shiftValue: '^',
      type: 'symbol',
    },
    {
      keyCode: 'Digit7',
      value: '7',
      shiftValue: '&',
      type: 'symbol',
    },
    {
      keyCode: 'Digit8',
      value: '8',
      shiftValue: '*',
      type: 'symbol',
    },
    {
      keyCode: 'Digit9',
      value: '9',
      shiftValue: '(',
      type: 'symbol',
    },
    {
      keyCode: 'Digit0',
      value: '0',
      shiftValue: ')',
      type: 'symbol',
    },
    {
      keyCode: 'Minus',
      value: '-',
      shiftValue: '_',
      type: 'symbol',
    },
    {
      keyCode: 'Equal',
      value: '=',
      shiftValue: '+',
      type: 'symbol',
    },
    {
      keyCode: 'Backspace',
      value: 'Backspace',
      shiftValue: 'Backspace',
      type: 'service',
    },
    {
      keyCode: 'Tab',
      value: 'Tab',
      shiftValue: 'Tab',
      type: 'service',
    },
    {
      keyCode: 'KeyQ',
      value: 'q',
      shiftValue: 'Q',
      type: 'letter',
    },
    {
      keyCode: 'KeyW',
      value: 'w',
      shiftValue: 'W',
      type: 'letter',
    },
    {
      keyCode: 'KeyE',
      value: 'e',
      shiftValue: 'E',
      type: 'letter',
    },
    {
      keyCode: 'KeyR',
      value: 'r',
      shiftValue: 'R',
      type: 'letter',
    },
    {
      keyCode: 'KeyT',
      value: 't',
      shiftValue: 'T',
      type: 'letter',
    },
    {
      keyCode: 'KeyY',
      value: 'y',
      shiftValue: 'Y',
      type: 'letter',
    },
    {
      keyCode: 'KeyU',
      value: 'u',
      shiftValue: 'U',
      type: 'letter',
    },
    {
      keyCode: 'KeyI',
      value: 'i',
      shiftValue: 'I',
      type: 'letter',
    },
    {
      keyCode: 'KeyO',
      value: 'o',
      shiftValue: 'O',
      type: 'letter',
    },
    {
      keyCode: 'KeyP',
      value: 'p',
      shiftValue: 'P',
      type: 'letter',
    },
    {
      keyCode: 'BracketLeft',
      value: '[',
      shiftValue: '{',
      type: 'symbol',
    },
    {
      keyCode: 'BracketRight',
      value: ']',
      shiftValue: '}',
      type: 'symbol',
    },
    {
      keyCode: 'Backslash',
      value: '\\',
      shiftValue: '|',
      type: 'symbol',
    },
    {
      keyCode: 'Delete',
      value: 'Del',
      shiftValue: 'Del',
      type: 'service',
    },
    {
      keyCode: 'CapsLock',
      value: 'CapsLock',
      shiftValue: 'CapsLock',
      type: 'activatable',
    },
    {
      keyCode: 'KeyA',
      value: 'a',
      shiftValue: 'A',
      type: 'letter',
    },
    {
      keyCode: 'KeyS',
      value: 's',
      shiftValue: 'S',
      type: 'letter',
    },
    {
      keyCode: 'KeyD',
      value: 'd',
      shiftValue: 'D',
      type: 'letter',
    },
    {
      keyCode: 'KeyF',
      value: 'f',
      shiftValue: 'F',
      type: 'letter',
    },
    {
      keyCode: 'KeyG',
      value: 'g',
      shiftValue: 'G',
      type: 'letter',
    },
    {
      keyCode: 'KeyH',
      value: 'h',
      shiftValue: 'H',
      type: 'letter',
    },
    {
      keyCode: 'KeyJ',
      value: 'j',
      shiftValue: 'J',
      type: 'letter',
    },
    {
      keyCode: 'KeyK',
      value: 'k',
      shiftValue: 'K',
      type: 'letter',
    },
    {
      keyCode: 'KeyL',
      value: 'l',
      shiftValue: 'L',
      type: 'letter',
    },
    {
      keyCode: 'Semicolon',
      value: ';',
      shiftValue: ':',
      type: 'symbol',
    },
    {
      keyCode: 'Quote',
      value: '\'',
      shiftValue: '"',
      type: 'symbol',
    },
    {
      keyCode: 'Enter',
      value: 'Enter',
      shiftValue: 'Enter',
      type: 'service',
    },
    {
      keyCode: 'ShiftLeft',
      value: 'Shift',
      shiftValue: 'Shift',
      type: 'service',
    },
    {
      keyCode: 'KeyZ',
      value: 'z',
      shiftValue: 'Z',
      type: 'letter',
    },
    {
      keyCode: 'KeyX',
      value: 'x',
      shiftValue: 'X',
      type: 'letter',
    },
    {
      keyCode: 'KeyC',
      value: 'c',
      shiftValue: 'C',
      type: 'letter',
    },
    {
      keyCode: 'KeyV',
      value: 'v',
      shiftValue: 'V',
      type: 'letter',
    },
    {
      keyCode: 'KeyB',
      value: 'b',
      shiftValue: 'B',
      type: 'letter',
    },
    {
      keyCode: 'KeyN',
      value: 'n',
      shiftValue: 'N',
      type: 'letter',
    },
    {
      keyCode: 'KeyM',
      value: 'm',
      shiftValue: 'M',
      type: 'letter',
    },
    {
      keyCode: 'Comma',
      value: ',',
      shiftValue: '<',
      type: 'symbol',
    },
    {
      keyCode: 'Period',
      value: '.',
      shiftValue: '>',
      type: 'symbol',
    },
    {
      keyCode: 'Slash',
      value: '/',
      shiftValue: '?',
      type: 'symbol',
    },
    {
      keyCode: 'ArrowUp',
      value: '',
      shiftValue: '',
      type: 'service',
    },
    {
      keyCode: 'ShiftRight',
      value: 'Shift',
      shiftValue: 'Shift',
      type: 'service',
    },
    {
      keyCode: 'ControlLeft',
      value: 'Ctrl',
      shiftValue: 'Ctrl',
      type: 'service',
    },
    {
      keyCode: 'MetaLeft',
      value: 'Win',
      shiftValue: 'Win',
      type: 'service',
    },
    {
      keyCode: 'AltLeft',
      value: 'Alt',
      shiftValue: 'Alt',
      type: 'service',
    },
    {
      keyCode: 'Space',
      value: ' ',
      shiftValue: ' ',
      type: 'symbol',
    },
    {
      keyCode: 'AltRight',
      value: 'Alt',
      shiftValue: 'Alt',
      type: 'service',
    },
    {
      keyCode: 'ArrowLeft',
      value: '',
      shiftValue: '',
      type: 'service',
    },
    {
      keyCode: 'ArrowDown',
      value: '',
      shiftValue: '',
      type: 'service',
    },
    {
      keyCode: 'ArrowRight',
      value: '',
      shiftValue: '',
      type: 'service',
    },
    {
      keyCode: 'ControlRight',
      value: 'Ctrl',
      shiftValue: 'Ctrl',
      type: 'service',
    },
  ],
  RU: [
    {
      keyCode: 'Backquote',
      value: 'ё',
      shiftValue: 'Ё',
      type: 'letter',
    },
    {
      keyCode: 'Digit1',
      value: '1',
      shiftValue: '!',
      type: 'symbol',
    },
    {
      keyCode: 'Digit2',
      value: '2',
      shiftValue: '"',
      type: 'symbol',
    },
    {
      keyCode: 'Digit3',
      value: '3',
      shiftValue: '№',
      type: 'symbol',
    },
    {
      keyCode: 'Digit4',
      value: '4',
      shiftValue: ';',
      type: 'symbol',
    },
    {
      keyCode: 'Digit5',
      value: '5',
      shiftValue: '%',
      type: 'symbol',
    },
    {
      keyCode: 'Digit6',
      value: '6',
      shiftValue: ':',
      type: 'symbol',
    },
    {
      keyCode: 'Digit7',
      value: '7',
      shiftValue: '?',
      type: 'symbol',
    },
    {
      keyCode: 'Digit8',
      value: '8',
      shiftValue: '*',
      type: 'symbol',
    },
    {
      keyCode: 'Digit9',
      value: '9',
      shiftValue: '(',
      type: 'symbol',
    },
    {
      keyCode: 'Digit0',
      value: '0',
      shiftValue: ')',
      type: 'symbol',
    },
    {
      keyCode: 'Minus',
      value: '-',
      shiftValue: '_',
      type: 'symbol',
    },
    {
      keyCode: 'Equal',
      value: '=',
      shiftValue: '+',
      type: 'symbol',
    },
    {
      keyCode: 'Backspace',
      value: 'Backspace',
      shiftValue: 'Backspace',
      type: 'service',
    },
    {
      keyCode: 'Tab',
      value: 'Tab',
      shiftValue: 'Tab',
      type: 'service',
    },
    {
      keyCode: 'KeyQ',
      value: 'й',
      shiftValue: 'Й',
      type: 'letter',
    },
    {
      keyCode: 'KeyW',
      value: 'ц',
      shiftValue: 'Ц',
      type: 'letter',
    },
    {
      keyCode: 'KeyE',
      value: 'у',
      shiftValue: 'У',
      type: 'letter',
    },
    {
      keyCode: 'KeyR',
      value: 'к',
      shiftValue: 'К',
      type: 'letter',
    },
    {
      keyCode: 'KeyT',
      value: 'е',
      shiftValue: 'Е',
      type: 'letter',
    },
    {
      keyCode: 'KeyY',
      value: 'н',
      shiftValue: 'Н',
      type: 'letter',
    },
    {
      keyCode: 'KeyU',
      value: 'г',
      shiftValue: 'Г',
      type: 'letter',
    },
    {
      keyCode: 'KeyI',
      value: 'ш',
      shiftValue: 'Ш',
      type: 'letter',
    },
    {
      keyCode: 'KeyO',
      value: 'щ',
      shiftValue: 'Щ',
      type: 'letter',
    },
    {
      keyCode: 'KeyP',
      value: 'з',
      shiftValue: 'З',
      type: 'letter',
    },
    {
      keyCode: 'BracketLeft',
      value: 'х',
      shiftValue: 'Х',
      type: 'letter',
    },
    {
      keyCode: 'BracketRight',
      value: 'ъ',
      shiftValue: 'Ъ',
      type: 'letter',
    },
    {
      keyCode: 'Backslash',
      value: '\\',
      shiftValue: '/',
      type: 'symbol',
    },
    {
      keyCode: 'Delete',
      value: 'Del',
      shiftValue: 'Del',
      type: 'service',
    },
    {
      keyCode: 'CapsLock',
      value: 'CapsLock',
      shiftValue: 'CapsLock',
      type: 'activatable',
    },
    {
      keyCode: 'KeyA',
      value: 'ф',
      shiftValue: 'Ф',
      type: 'letter',
    },
    {
      keyCode: 'KeyS',
      value: 'ы',
      shiftValue: 'Ы',
      type: 'letter',
    },
    {
      keyCode: 'KeyD',
      value: 'в',
      shiftValue: 'В',
      type: 'letter',
    },
    {
      keyCode: 'KeyF',
      value: 'а',
      shiftValue: 'А',
      type: 'letter',
    },
    {
      keyCode: 'KeyG',
      value: 'п',
      shiftValue: 'П',
      type: 'letter',
    },
    {
      keyCode: 'KeyH',
      value: 'р',
      shiftValue: 'Р',
      type: 'letter',
    },
    {
      keyCode: 'KeyJ',
      value: 'о',
      shiftValue: 'О',
      type: 'letter',
    },
    {
      keyCode: 'KeyK',
      value: 'л',
      shiftValue: 'Л',
      type: 'letter',
    },
    {
      keyCode: 'KeyL',
      value: 'д',
      shiftValue: 'Д',
      type: 'letter',
    },
    {
      keyCode: 'Semicolon',
      value: 'ж',
      shiftValue: 'Ж',
      type: 'letter',
    },
    {
      keyCode: 'Quote',
      value: 'э',
      shiftValue: 'Э',
      type: 'letter',
    },
    {
      keyCode: 'Enter',
      value: 'Enter',
      shiftValue: 'Enter',
      type: 'service',
    },
    {
      keyCode: 'ShiftLeft',
      value: 'Shift',
      shiftValue: 'Shift',
      type: 'service',
    },
    {
      keyCode: 'KeyZ',
      value: 'я',
      shiftValue: 'Я',
      type: 'letter',
    },
    {
      keyCode: 'KeyX',
      value: 'ч',
      shiftValue: 'Ч',
      type: 'letter',
    },
    {
      keyCode: 'KeyC',
      value: 'с',
      shiftValue: 'С',
      type: 'letter',
    },
    {
      keyCode: 'KeyV',
      value: 'м',
      shiftValue: 'М',
      type: 'letter',
    },
    {
      keyCode: 'KeyB',
      value: 'и',
      shiftValue: 'И',
      type: 'letter',
    },
    {
      keyCode: 'KeyN',
      value: 'т',
      shiftValue: 'Т',
      type: 'letter',
    },
    {
      keyCode: 'KeyM',
      value: 'ь',
      shiftValue: 'Ь',
      type: 'letter',
    },
    {
      keyCode: 'Comma',
      value: 'б',
      shiftValue: 'Б',
      type: 'letter',
    },
    {
      keyCode: 'Period',
      value: 'ю',
      shiftValue: 'Ю',
      type: 'letter',
    },
    {
      keyCode: 'Slash',
      value: '.',
      shiftValue: ',',
      type: 'symbol',
    },
    {
      keyCode: 'ArrowUp',
      value: '',
      shiftValue: '',
      type: 'service',
    },
    {
      keyCode: 'ShiftRight',
      value: 'Shift',
      shiftValue: 'Shift',
      type: 'service',
    },
    {
      keyCode: 'ControlLeft',
      value: 'Ctrl',
      shiftValue: 'Ctrl',
      type: 'service',
    },
    {
      keyCode: 'MetaLeft',
      value: 'Win',
      shiftValue: 'Win',
      type: 'service',
    },
    {
      keyCode: 'AltLeft',
      value: 'Alt',
      shiftValue: 'Alt',
      type: 'service',
    },
    {
      keyCode: 'Space',
      value: ' ',
      shiftValue: ' ',
      type: 'symbol',
    },
    {
      keyCode: 'AltRight',
      value: 'Alt',
      shiftValue: 'Alt',
      type: 'service',
    },
    {
      keyCode: 'ArrowLeft',
      value: '',
      shiftValue: '',
      type: 'service',
    },
    {
      keyCode: 'ArrowDown',
      value: '',
      shiftValue: '',
      type: 'service',
    },
    {
      keyCode: 'ArrowRight',
      value: '',
      shiftValue: '',
      type: 'service',
    },
    {
      keyCode: 'ControlRight',
      value: 'Ctrl',
      shiftValue: 'Ctrl',
      type: 'service',
    },
  ],
};

export default KEY_LAYOUTS;
